// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const createBrowserClient = (storageKey: string) =>
  createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      storageKey,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

// Merchant auth + app-wide data client
export const supabase = createBrowserClient('openalert.merchant.auth');

// Consumer auth client (isolated storage/session from merchant auth)
export const supabaseConsumer = createBrowserClient('openalert.consumer.auth');
